### ISSUE TITLE
RepoSense Compatibility

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#107]
https://nus-cs2113-ay2021s1.github.io/website/schedule/week10/project.html#4-make-the-code-reposense-compatible

**Comment by sevenseasofbri** [comment]
Yo we gotta do this too I forgot abt this

**Comment by hughjazzman** [comment]
https://nus-cs2113-ay2021s1.github.io/tp-dashboard/#breakdown=true&search=AY2021S1-CS2113T-W13-3%2Ftp&sort=groupTitle&sortWithin=title&since=2020-09-27&timeframe=commit&mergegroup=&groupSelect=groupByRepos&checkedFileTypes=docs~functional-code~test-code~other

Last chance for checks!
