### ISSUE TITLE
Update All JavaDoc

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#110]
Including classes.

**Comment by sevenseasofbri** [comment]
gg

**Comment by sevenseasofbri** [comment]
@AY2021S1-CS2113T-W13-3/developers halp who does what

**Comment by hughjazzman** [comment]
@dorianfong98 

Need to do JavaDoc for all classes also.

Follow https://se-education.org/guides/conventions/java/index.html#comments.

Can also follow https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#examples.
