### ISSUE TITLE
DG comments

### ISSUE THREAD

**Issue by nishanthelango** [AY2021S1-CS2113T-W13-3/tp#120]
- [x] You can refer to this forum post: https://github.com/nus-cs2113-AY2021S1/forum/issues/112
to remove the non-standard notations from the plantUML diagrams.

- [x] (Figure 8) If the LrTemplate() call is a constructor, the arrow should point to the :LrTemplate object, and the activity bar should be connected to :LrTemplate. Please review the other sequence diagrams and constructors as well.

- [x]  (Figure 10) Consider removing the redundant “capacitor.” in the capacitor method calls.
![image](https://user-images.githubusercontent.com/37863640/97532298-fea4f100-19f0-11eb-9f8b-029061f7a871.png)

- [x]  (Figure 18) Consider using a Class Diagram if you want to show the inheritance relationship:  
![image](https://user-images.githubusercontent.com/37863640/97532658-c05c0180-19f1-11eb-8c50-5d792d8b419e.png)

- [x] (Figure 16)  Consider removing the parentheses in AndGate() to avoid confusion with methods 
![image](https://user-images.githubusercontent.com/37863640/97532365-2431fa80-19f1-11eb-9a96-bc95ec86ceb5.png)

- [x] (Figure 20) Try to display the alt paths like this:
![image](https://user-images.githubusercontent.com/37863640/97532404-3875f780-19f1-11eb-8b27-23639d420676.png)
![image](https://user-images.githubusercontent.com/37863640/97532408-3c097e80-19f1-11eb-9d10-060c5c8e817e.png)

- [x]  (Figure 22) Is this supposed to be a solid line? This part of the sequence diagram isn't very clear.
![image](https://user-images.githubusercontent.com/37863640/97532428-46c41380-19f1-11eb-9cbf-3fed3bd4f98c.png)

- [ ] (Figure 22) Can this be replaced with an opt block instead? 
![image](https://user-images.githubusercontent.com/37863640/97532493-74a95800-19f1-11eb-8929-7df60b22aee2.png)

- [x]  (Figure 15) Consider following the  standard UML notation for class diagrams as shown here: https://nus-cs2113-ay2021s1.github.io/website/se-book-adapted/chapters/uml.html#class-diagrams
Take note of the positioning of the variable types, and the omission of the method bodies. 
![image](https://user-images.githubusercontent.com/37863640/97532512-7d9a2980-19f1-11eb-93ff-7eb6a5ec23a7.png)

**Comment by hughjazzman** [comment]
Hi Nishanth, thanks for the review! Is it ok if you check out the current PR #119 DG to see if some of these issues are resolved?

https://hughjazzman.github.io/tp/DeveloperGuide.html

**Comment by nishanthelango** [comment]
I've marked the resolved issues as done!

**Comment by sevenseasofbri** [comment]
Hi @nishanthelango thanks for the review! :D About this diagram:
![image](https://user-images.githubusercontent.com/57522870/97538271-16817280-19fb-11eb-845b-fbcca96f910c.png)
Yup it's supposed to be a solid line, thanks for pointing out! I just wanted to ask if this notation is ok for _object creation_ in sequence diagrams, because I can't seem to find a way to do it the way it's been [specified in the textbook](https://nus-cs2113-ay2021s1.github.io/website/book/modeling/modelingBehaviors/sequenceDiagramsBasic/) when I use PlantUML.

(Update: I'll still look around though, I'm kinda new to PUML lol)

**Comment by nishanthelango** [comment]
Hi @sevenseasofbri I'm actually not that familiar with plantUML so I'm not sure, but please continue searching  for ways to display the object creation while I check with prof!

**Comment by nishanthelango** [comment]
@sevenseasofbri I looked through the plantUML docs, I think you can use the 'create' keyword for object creation

@startuml
Bob -> Alice : hello
create Other
Alice -> Other : new
activate Other
Other --> Alice
deactivate Other
Alice --> Bob : ok
@enduml
 
generates 
 
![image](https://user-images.githubusercontent.com/37863640/97560397-90c0ef80-1a19-11eb-8660-dcd14a0aea16.png)

**Comment by sevenseasofbri** [comment]
@nishanthelango OHH thank you so much! (I should've looked at the docs better oof) :D

**Comment by hughjazzman** [comment]
> If the LrTemplate() call is a constructor, the arrow should point to the :LrTemplate object, and the activity bar should be connected to :LrTemplate. Please review the other sequence diagrams and constructors as well.

> @sevenseasofbri I looked through the plantUML docs, I think you can use the 'create' keyword for object creation

@nishanthelango Ah I should've looked too, makes a lot of sense that constructors can be called that way within plantUML. Thanks!

**Comment by hughjazzman** [comment]
> (Figure 16) Consider removing the parentheses in AndGate() to avoid confusion with methods

Is this perhaps clearer?

![TemplateBooleanCommand](https://user-images.githubusercontent.com/53231968/97584865-7267ed80-1a33-11eb-9655-db0525ecc09a.png)

**Comment by hughjazzman** [comment]
> (Figure 16) Consider removing the parentheses in AndGate() to avoid confusion with methods

@nishanthelango Is this perhaps clearer?

![TemplateBooleanCommand](https://user-images.githubusercontent.com/53231968/97585254-e7d3be00-1a33-11eb-8b96-4db79c00ac2e.png)

**Comment by nishanthelango** [comment]
> > (Figure 16) Consider removing the parentheses in AndGate() to avoid confusion with methods
> 
> @nishanthelango Is this perhaps clearer?
> 
> ![TemplateBooleanCommand](https://user-images.githubusercontent.com/53231968/97585254-e7d3be00-1a33-11eb-8b96-4db79c00ac2e.png)

Yes this is clearer!

**Comment by hughjazzman** [comment]
> (Figure 22) Can this be replaced with an opt block instead?

@sevenseasofbri  Is this one fixed yet?

**Comment by sevenseasofbri** [comment]
@hughjazzman yup

**Comment by sevenseasofbri** [comment]
@hughjazzman lol i forgot
