### ISSUE TITLE
Implementation Issues

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#155]
- [x] #123 
     - **`SetCircuitCommand`**: 
         - Update `SetCircuitCommand#toString()` to have voltage source also print template.
- [x] #129, #135, 
     - **`TutorialBooleanCommand`**: 
         - Also part of #154, update instructions on how to use `tutorial boolean`. 
             * `add C GATE` should be changed to an extremely specific example with no freedom of choice
- [x] #137, #142, #143, #144 
     - **`TutorialCircuitCommand`**: 
         * Check that the user is following the commands to the T, remove possibility for unavailable components to be added
         * Check that voltage cannot be set instead of a load component.
- [x] #136, #145 
     - **`AddCircuitCommand`**: 
         - Adding new components should print the old component. Make copy of old object.
- [x] #139 
     - **`Ui`**: 
         - Update `Ui#printGreeting()` with summary
- [x] #140
     - **`Ui`**: 
         - Update `Ui#LOGO` positioning
- [x] #146
     - **`BooleanTemplate`**: 
         - Prevent setting of unavailable indices in `BooleanTemplate`
- [x] #147
     - **ALL**: 
         - Customise Exceptions for every package.
- [x] #148, #149, #150 
     - **`AddCircuitCommand`**: 
         - Double check adding component that is not yet set. Can also change 0 values to "not set" when printing instead
- [x] #151, #152, #153 
     - **`Gate`**: 
         - Double check output of Xnor, Nor, Nand gates.

**Comment by hughjazzman** [comment]
@oasisbeatle You can look at @sevenseasofbri for reference on the clarity for `TutorialBooleanCommand`.

**Comment by sevenseasofbri** [comment]
@hughjazzman is @PraveenElango doing the additions for the tutorialbooleancommand or @oasisbeatle ?

**Comment by hughjazzman** [comment]
@sevenseasofbri Initially you said @oasisbeatle right? Did @PraveenElango want to do it insteaed?

**Comment by sevenseasofbri** [comment]
@hughjazzman yup! i had thought since @oasisbeatle had done the tutorial command in the first place he could make changes. However i think @PraveenElango offered to do it today
