### ISSUE TITLE
Add JUnit Testing

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#29]
https://nus-cs2113-ay2021s1.github.io/website/schedule/week8/project.html#4-add-some-junit-tests

**Comment by hughjazzman** [comment]
Assigned JUnit Testing classes:

| Class       | Person                                           |
|-------------|--------------------------------------------------|
| `Command`   | @sevenseasofbri will do `HelpCommand` subclass, @dorianfong98 the rest |
| `Component` | @oasisbeatle  |
| `Parser`    | @hughjazzman  |
| `Template`  | @PraveenElango  |
| `Ui` | @sevenseasofbri |

**Comment by sevenseasofbri** [comment]
Okay sounds good!

**Comment by hughjazzman** [comment]
Being the last task of milestone v1.0, we can follow this after closing: https://nus-cs2113-ay2021s1.github.io/website/schedule/week9/project.html#using-milestones

* A working product tagged.
* CI passing.
* Milestone updated to match the product.
* Milestone closed.
