### ISSUE TITLE
Create Developer Guide

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#40]
https://nus-cs2113-ay2021s1.github.io/website/schedule/week10/project.html#2-update-the-dg-with-design-details-important

* Each member should describe the implementation of at least one enhancement she has added (or planning to add).
Expected length: 1+ page per person
* Describing the design at a multiple-levels (e.g., first, describe at architecture-level, then describe at component-level) is optional. It is also acceptable to have one Design & Implementation section in which you describe the entire thing at the class- and object-level.
* The description can contain things such as,
    * How the feature is implemented (or is going to be implemented).
    * Why it is implemented that way.
    * Alternatives considered.
* Use UML diagrams.

Here is an example of the Dev Guide: https://se-education.org/addressbook-level3/DeveloperGuide.html

**Comment by hughjazzman** [comment]
@sevenseasofbri will update Glossary once everyone has updated the Dev Guide. #73

**Comment by hughjazzman** [comment]
On these two points:

* Why it is implemented that way.
* Alternatives considered.

I believe we can add this for the `CircuitTemplate` as well as the `BinaryTree`.

Can @oasisbeatle or @dorianfong98 do a short write-up for `CircuitTemplate` and @sevenseasofbri or @dorianfong98 do one for `BinaryTree`?

**Comment by sevenseasofbri** [comment]
> Can @oasisbeatle or @dorianfong98 do a short write-up for `CircuitTemplate` and @sevenseasofbri or @dorianfong98 do one for `BinaryTree`?

Okie I'll do it

**Comment by sevenseasofbri** [comment]
Yo I'll add this soon before class perhaps

**Comment by hughjazzman** [comment]
We can also add future (hypothetical) features past v2.1.
