### ISSUE TITLE
Add Assertions

### ISSUE THREAD

**Issue by sevenseasofbri** [AY2021S1-CS2113T-W13-3/tp#47]
To make the code more defensive. 
https://nus-cs2113-ay2021s1.github.io/website/schedule/week9/project.html#1-make-the-code-more-defensive

**Comment by sevenseasofbri** [comment]
Task Assignment:

Package | Person
-- | --
Command | @sevenseasofbri HelpCommand, CalculateCommand, AddCommand, SummaryCommand
Command |  @dorianfong98 ExitCommand, SetCommand, Command, TemplateCommand
Component | @oasisbeatle
Parser | @hughjazzman
Template | @PraveenElango

**Comment by hughjazzman** [comment]
@dorianfong98 `Command` classes done?
