### ISSUE TITLE
Calculation of Effective Resistance, Capacitance

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#5]
As a new CEG/EE Student, I can calculate/verify my calculations of effective resistance, total capacitance, etc via CLI so that I can quickly and accurately do so for a chosen configuration via CLI, and not 3rd party software that I have to install/load online.

Requires #3.

Based on the [User Guide section](https://github.com/AY2021S1-CS2113T-W13-3/tp/blob/master/docs/UserGuide.md#calculate-effective-value-calc):

> Calculates the effective value based on the components and their configuration. If calculating `reff`, `ceff`, or `leff`, the component must be part of the current circuit template.
> 
> Format: `calc EFF_VALUE`
> 
> * The `EFF_VALUE` can be chosen from the following 5 - `reff`, `ceff`, `leff`, `current`, `power`
>     * `reff` is the effective resistance
>     * `ceff` is the effective capacitance
>     * `leff` is the effective inductance
>     * `current` is the current flowing through the power supply
>     * `power` is the power supplied by the power supply
> 
> Example of usage:
> 
> `calc ceff`

**Comment by hughjazzman** [comment]
Todo:

* Take a look at `Parser.prepareCalc()`.
* Take a look at `Command` and other subclasses.
* Create `CalculateCommand` class.
* Implement `CalculateCommand.execute()` method.
* Use `Template` calculate methods to get values.
* Use`Ui` to print result.
* Add JUnit test(s) for `CalculateCommand`.

**Comment by sevenseasofbri** [comment]
Ok will add this
