### ISSUE TITLE
Print Template

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#68]
As a CEG/EE Student, I want to **print the current template** I am working on so that I can Find out my current configuration.

**Comment by hughjazzman** [comment]
Add a `PrintCommand` to print both `CircuitTemplate` and `BooleanTemplate`.

**Comment by hughjazzman** [comment]
Not implemented in `v2.0`.

**Comment by sevenseasofbri** [comment]
no
