### ISSUE TITLE
Add JUnit Testing v2.0

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#72]

**Comment by hughjazzman** [comment]
@dorianfong98 to do `BinaryTree`
@sevenseasofbri to do `BooleanTemplate`

**Comment by dorianfong98** [comment]
Update: completed JUnit Testing for `BinaryTree`

**Comment by oasisbeatle** [comment]
Update 
@sevenseasofbri to do `CalculateBooleanCommandTest`
@oasisbeatle to do `AddBooleanCommandTest`
@hughjazzman to do `SetBooleanCommandTest`
