### ISSUE TITLE
Update BooleanParser

### ISSUE THREAD

**Issue by sevenseasofbri** [AY2021S1-CS2113T-W13-3/tp#89]
To accept lower case boolean signals.

**Comment by sevenseasofbri** [comment]
+ With HelpCommandParser

**Comment by hughjazzman** [comment]
@sevenseasofbri Add the parsing into `Parser`,`BooleanParser` and `CircuitParser`, to return `TutorialBooleanCommand` and `TutorialCircuitCommand`.
