### ISSUE TITLE
Add Implementation Considerations

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#95]
Mentioned in #40. Explain in **DevGuide**:

* Why it is implemented that way.
* Alternatives considered.

|Class/Feature|Person|
|-|-|
|`CircuitTemplate`| @oasisbeatle |
|`BinaryTree`| @sevenseasofbri |

**Comment by oasisbeatle** [comment]
#116

**Comment by hughjazzman** [comment]
Merged in #116.
